services:
  neo4j:
    image: neo4j
    container_name: neo4j_container
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_memory_heap_initial__size=4G
      - NEO4J_server_memory_heap_max__size=8G
      - NEO4J_dbms_memory_transaction_total_max=8G
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data_neo4j:/data
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "--non-interactive", "RETURN 1;"]
      interval: 30s
      timeout: 60s
      retries: 3


  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 30s
      timeout: 60s
      retries: 3

  prometheus:
    build: .
    container_name: prometheus
    ports:
      - "9001:9001"
    environment:
      - PROMETHEUS_LOGGING_LEVEL="DEBUG"
      - PROMETHEUS_NEO4J_URI="bolt://localhost:7687"
      - PROMETHEUS_NEO4J_USERNAME=neo4j
      - PROMETHEUS_NEO4J_PASSWORD=password
      - PROMETHEUS_NEO4J_BATCH_SIZE=1000
      - PROMETHEUS_KNOWLEDGE_GRAPH_MAX_AST_DEPTH=4
      - PROMETHEUS_KNOWLEDGE_GRAPH_CHUNK_SIZE=10000
      - PROMETHEUS_KNOWLEDGE_GRAPH_CHUNK_OVERLAP=1000
      - PROMETHEUS_MAX_TOKEN_PER_NEO4J_RESULT=5000
      - PROMETHEUS_MODEL=${PROMETHEUS_MODEL}
      - PROMETHEUS_ANTHROPIC_API_KEY=${PROMETHEUS_ANTHROPIC_API_KEY}
      - PROMETHEUS_GEMINI_API_KEY=${PROMETHEUS_GEMINI_API_KEY}
      - PROMETHEUS_OPENAI_API_KEY=${PROMETHEUS_OPENAI_API_KEY}
      - PROMETHEUS_WORKING_DIRECTORY="/app/working_dir"
      - PROMETHEUS_GITHUB_ACCESS_TOKEN=${PROMETHEUS_GITHUB_ACCESS_TOKEN}
      - PROMETHEUS_POSTGRES_URI="postgresql://postgres:password@localhost:5432/postgres?sslmode=disable"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
    depends_on:
      neo4j:
        condition: service_healthy
      postgres:
        condition: service_healthy
    develop:
      watch:
        - path: .
          target: /app
          action: sync+restart