[default]
logging_level = "DEBUG"

# neo4j settings
neo4j_uri = "bolt://localhost:7687"
neo4j_username = "neo4j"
neo4j_password = "password"
neo4j_batch_size = 1000

# knowledge_graph settings
working_directory = "/tmp/"
knowledge_graph_max_ast_depth = 3
knowledge_graph_chunk_size = 10000
knowledge_graph_chunk_overlap = 1000
max_token_per_neo4j_result = 10000

# LLM settings
advanced_model = "claude-3-5-sonnet-20241022"
base_model = "claude-3-5-haiku-20241022"
anthropic_api_key = "anthropic_api_key"
gemini_api_key = "gemini_api_key"
openai_api_key = "openai_api_key"
openrouter_api_key = "openrouter_api_key"

# github settings
github_access_token = "github_access_token"

# postgres settings
postgres_uri = "postgresql://postgres:password@localhost:5432/postgres?sslmode=disable"
